### ISSUE TITLE
Failing on ESLint 6.x

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/eslines#18]
```
/home/circleci/repo/node_modules/eslines/src/cli.js:44
				throw ex;
				^

Error: Problem loading formatter: eslint/lib/formatters/stylish
Error: Cannot find module 'eslint/lib/formatters/stylish'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at getESLintFormatter (/home/circleci/repo/node_modules/eslines/src/cli.js:40:12)
    at module.exports (/home/circleci/repo/node_modules/eslines/src/cli.js:104:21)
    at Socket.process.stdin.on (/home/circleci/repo/node_modules/eslines/index.js:41:17)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
npm ERR! code ELIFECYCLE
```

**Comment by sjinks** [comment]
Hi, I think this has already been fixed (or at least I am not able to reproduce this issue anymore). Could you please take a look?

**Comment by nickdaugherty** [comment]
👍 with ES 7.x out, probably not worth worrying about this anymore anyway.
